// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

/*
Package blog is a generated protocol buffer package.

It is generated from these files:
	proto/blog.proto

It has these top-level messages:
	InsertRequest
	InsertResponse
	SelectRequest
	SelectResponse
*/
package blog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InsertRequest struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *InsertRequest) Reset()                    { *m = InsertRequest{} }
func (m *InsertRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()               {}
func (*InsertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InsertRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InsertRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *InsertRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type InsertResponse struct {
}

func (m *InsertResponse) Reset()                    { *m = InsertResponse{} }
func (m *InsertResponse) String() string            { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()               {}
func (*InsertResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SelectRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *SelectRequest) Reset()                    { *m = SelectRequest{} }
func (m *SelectRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()               {}
func (*SelectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SelectRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SelectResponse struct {
	Id      int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *SelectResponse) Reset()                    { *m = SelectResponse{} }
func (m *SelectResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()               {}
func (*SelectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SelectResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SelectResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SelectResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*InsertRequest)(nil), "blog.InsertRequest")
	proto.RegisterType((*InsertResponse)(nil), "blog.InsertResponse")
	proto.RegisterType((*SelectRequest)(nil), "blog.SelectRequest")
	proto.RegisterType((*SelectResponse)(nil), "blog.SelectResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlogService service

type BlogServiceClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := grpc.Invoke(ctx, "/blog.BlogService/Insert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	out := new(SelectResponse)
	err := grpc.Invoke(ctx, "/blog.BlogService/Select", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlogService service

type BlogServiceServer interface {
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _BlogService_Insert_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _BlogService_Select_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/blog.proto",
}

func init() { proto.RegisterFile("proto/blog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xca, 0xc9, 0x4f, 0xd7, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x7f, 0x2e,
	0x5e, 0xcf, 0xbc, 0xe2, 0xd4, 0xa2, 0x92, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x3e,
	0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x11,
	0x2e, 0xd6, 0x92, 0xcc, 0x92, 0x9c, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47,
	0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf, 0x24, 0x35, 0xaf, 0x44, 0x82, 0x19, 0x2c, 0x0e, 0xe3,
	0x2a, 0x09, 0x70, 0xf1, 0xc1, 0x0c, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x92, 0xe7, 0xe2,
	0x0d, 0x4e, 0xcd, 0x49, 0x4d, 0xc6, 0x65, 0x85, 0x52, 0x00, 0x17, 0x1f, 0x4c, 0x01, 0x44, 0x0b,
	0xa5, 0x8e, 0x30, 0xaa, 0xe6, 0xe2, 0x76, 0xca, 0xc9, 0x4f, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x15, 0x32, 0xe5, 0x62, 0x83, 0xb8, 0x49, 0x48, 0x58, 0x0f, 0x1c, 0x02, 0x28, 0x5e, 0x96,
	0x12, 0x41, 0x15, 0x84, 0x3a, 0x9b, 0x01, 0xa4, 0x0d, 0xe2, 0x2e, 0x98, 0x36, 0x14, 0x6f, 0xc0,
	0xb4, 0xa1, 0x3a, 0x5d, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0xbe, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6d, 0x64, 0x82, 0xc4, 0x73, 0x01, 0x00, 0x00,
}
